### ISSUE TITLE
Varying parameters as input?

### ISSUE THREAD

**Issue by BachiLi** [joaoleal/CppADCodeGen#1]
Is it possible for cppadcodegen to accept parameters that we are not taken their derivatives as input?  For example, in the Hessian of Lagrangian (http://www.coin-or.org/CppAD/Doc/hes_lagrangian.cpp.htm) example, how do we generate code for the "Usefg" function, which takes the Lagrangian multipliers as input?

By the way, thanks for this wonderful piece of software.

**Comment by joaoleal** [comment]
Before compiling the code you can specify exactly which derivatives you are interested in.
For instance, for the sparse Hessian you can specify it like this:
```
ModelCSourceGen<double> cgen(fun, "myModelName");
std::vector<size_t> hRow(3), hCol(3); // not all elements need to be specified
jacRow[0] = 0;
hCol[0] = 0;
hRow[1] = 1;
hCol[1] = 0;
// (...)
cgen.setCreateSparseHessian(true);
cgen.setCustomSparseHessianElements(hRow, hCol);

ModelLibraryCSourceGen<double> libgen(cgen);
// (...)
```
If you do not request derivatives for a given variable it essentially becomes a parameter.

Therefore, for a Lagrangian, you only need to do something like this:
```
using namespace CppAD;
    using namespace CppAD::cg;

    typedef CG<double> CGD;
    typedef AD<CGD> ADCG;

    size_t nCtr = 2; // number of constraints
    size_t nVar = 3; // number of decision variables
    // independent variable vector
    std::vector<ADCG> v(nCtr + nVar);
    Independent(v);

    std::vector<ADCG> x(nVar); // decision variables
    for (size_t i = 0; i < nVar; ++i)
        x[i] = v[i];
    std::vector<ADCG> lam(nCtr); // Lagrangian multipliers
    for (size_t i = 0; i < nCtr; ++i)
        lam[i] = v[nVar + i];

    // dependent variable vector 
    std::vector<ADCG> lag(1);

    /**
     * the model of the Lagrangian
     */
    lag[0] = 2 * x[0] * x[0] + 3 * x[1] * x[1] + 4 * x[2] * x[2]; // objective
    lag[0] += lam[0] * (x[1] - 2 * x[2]); // constraint 1
    lag[0] += lam[1] * (x[0] * x[2]); // constraint 2

    ADFun<CGD> fun(v, lag);

    /**
     * Determine Hessian sparsity pattern
     */
    // determine the sparsity pattern
    typedef std::vector<std::set<size_t> > sparType;
    sparType sparsity = CppAD::extra::hessianSparsitySet<sparType, CGD>(fun); // this could be improved

    size_t n = fun.Domain();
    assert(sparsity.size() == n);

    std::vector<size_t> rows, cols;
    for (size_t i = 0; i < nVar; i++) {
        for (size_t j : sparsity[i]) {
            if (j >= nVar) break;
            rows.push_back(i);
            cols.push_back(j);
        }
    }

    /**
     * Create the dynamic library
     * (generates and compiles source code)
     */

    // generates source code
    ModelCSourceGen<double> cgen(fun, "Lagrangian");
    cgen.setCreateSparseHessian(true);
    cgen.setCustomSparseHessianElements(rows, cols);
    ModelLibraryCSourceGen<double> libgen(cgen);

    // compile source code
    DynamicModelLibraryProcessor<double> p(libgen);

    GccCompiler<double> compiler;
    DynamicLib<double>* dynamicLib = p.createDynamicLibrary(compiler);

    // save to files (not really required)
    SaveFilesModelLibraryProcessor<double> p2(libgen);
    p2.saveSources();

    /**
     * Use the dynamic library
     */
    GenericModel<double>* model = dynamicLib->model("Lagrangian");
    std::vector<double> V(v.size());
    V[0] = 2.5;
    V[1] = 3.5;
    V[2] = 4.5;
    V[3] = 5.5; // multiplier
    V[4] = 6.5; // multiplier
    std::vector<double> w(1, 1.0);
    std::vector<double> hess;
    std::vector<size_t> row, col;

    model->SparseHessian(V, w, hess, row, col); // there are other calls for sparse hessian

    // print out the result
    for (size_t i = 0; i < hess.size(); ++i)
        std::cout << "(" << row[i] << "," << col[i] << ") " << hess[i] << std::endl;

    delete model;
    delete dynamicLib;
```
If your (optimization??) problem only requires values from the Lagrangian you could use this code. Eventually you'll have to define the sparsity for the Jacobian too.

Nonetheless, if you only need the Hessian of the Lagrangian, Jacobian of the constraints and gradient of the objective you should consider not defining the Lagrangian explicitly but rather define a system of equations.
The Hessian calls allows you to define multipliers for each equation which might be exactly what you need. For a system of equation you actually get a weighted sum of each Hessian which is the same as the Hessian of your Lagrangian.

Did this help?

**Comment by BachiLi** [comment]
Thanks a lot for the detailed explanation, it is very helpful.  

My problem is to take the derivatives with respect to a subset of the variables, so the sparse Hessian solution does work for me.  I also found that I can use multi-level AD in CppAD to change the parameters:
https://github.com/coin-or/CppAD/blob/master/example/change_const.cpp

I think I will try and see which one has better performance.  Thanks!

**Comment by bradbell** [comment]
On 2/17/2015 7:37 AM, BachiLi wrote:
>
> Thanks a lot for the detailed explanation, it is very helpful.
>
> My problem is to take the derivatives with respect to a subset of the 
> variables, so the sparse Hessian solution does work for me. I also 
> found that I can use multi-level AD in CppAD to change the parameters:
> https://github.com/coin-or/CppAD/blob/master/example/change_const.cpp
>
> I think I will try and see which one has better performance. Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/joaoleal/CppADCodeGen/issues/1#issuecomment-74676596>.
>
Take a look at the following example
     http://www.coin-or.org/CppAD/Doc/sub_sparse_hes.cpp.xml

**Comment by BachiLi** [comment]
Cool, thanks!
