### ISSUE TITLE
Release calandar

### ISSUE THREAD

**Issue by jcarpent** [joaoleal/CppADCodeGen#20]
Is there any precise schedule for the next release?

I plan to package CppADCodeGen for homebrew (in https://github.com/Gepetto/homebrew-gepetto) and Linux systems (via http://robotpkg.openrobots.org/), and it would be nice to have a new release before that.

**Comment by bradbell** [comment]
The only schedule for CppAD is that at the beginning of each year a new stable version is created and the stable version only gets bug fixes, the API does not advance. See
https://github.com/coin-or/CppAD/releases

As for this change to the atomic functions, I hope to get to it soon.  One thing that may slow me down is that there are other improvements to the atomic functions I am considering and I would like to do that while I am changing that code.

Another new feature that you may want to consider is the conversion of an ADFun<Base> -> ADFun< AD<Base> > object. This makes it much simpler to create functions defined using derivatives of other  functions. See
https://coin-or.github.io/CppAD/doc/base2ad.htm

**Comment by jcarpent** [comment]
Got it. 
It seems reasonable for me, even if I think from time to time, it would be recommended to provide some patches (bug fixes, etc.).

Got it also for the second part of the discussion. Thanks for this feedback.

**Comment by joaoleal** [comment]
I guess an official release of CppADCodeGen for CppAD 2018 is overdue.
I'll make the release this weekend :)

**Comment by jcarpent** [comment]
Sounds perfect. Thanks!

**Comment by joaoleal** [comment]
Just waiting for Travis...
https://www.traviscistatus.com/
> Investigating - Builds seem to be not starting on travis-ci.org (open source). We are investigating the issue. 
> Oct 28, 10:35 UTC

**Comment by jcarpent** [comment]
@joaoleal Thank you very much for this release.
