### ISSUE TITLE
Multiple declaration of class ADFun

### ISSUE THREAD

**Issue by alexliniger** [joaoleal/CppADCodeGen#21]
I installed CppAD and CppADCodeGen, and tested all CppADCodeGen examples on two different PCs both running Ubuntu 16.4, and I always get the following error. 

> g++ -std=c++11 lagrangian.cpp -o lagrangian
> In file included from /usr/local/include/cppad/cg/cppadcg.hpp:77:0,
>                  from /usr/local/include/cppad/cg.hpp:18,
>                  from lagrangian.cpp:18:
> /usr/local/include/cppad/cg/declare_cg.hpp:28:7: error: redeclared with 1 template parameter
>  class ADFun;
>        ^
> In file included from /usr/include/cppad/base_require.hpp:163:0,
>                  from /usr/local/include/cppad/cg/cppadcg.hpp:71,
>                  from /usr/local/include/cppad/cg.hpp:18,
>                  from lagrangian.cpp:18:
> /usr/include/cppad/local/declare_ad.hpp:53:50: note: previous declaration ‘template<class Base, class RecBase> class CppAD::ADFun’ used 2 template parameters template <class Base, class RecBase=Base> class ADFun;

Does someone know what I did wrong, or is this an issue due to changes in CppAD? 

Thanks,
Alex

**Comment by joaoleal** [comment]
Hello Alex,

I'm using ubuntu 18.04 and I couldn't reproduce the issue.
Which version of CppAD and CppADCodeGen are you using?
How did you install the packages?

Could please try to install CppAD 2018 and then do the following steps:
```
mkdir build
cd build
ccmake path/to/cppadcodegen # <<< replace with the correct path
cd example
make example_lagrangian
```
I see the following output:
```
joao@megafox:~/Development/CppADCodeGen-master/cmake-build-debug/example$ make example_lagrangian
Building CXX object example/CMakeFiles/lagrangian.dir/lagrangian.cpp.o
Linking CXX executable lagrangian
Built target lagrangian
(0,0) 4
(0,2) 6.5
(1,1) 6
(2,0) 6.5
(2,2) 8
Built target example_lagrangian
```

**Comment by alexliniger** [comment]
Thanks for the instructions. I was able to get everything running by following your continuous integration code. What i found is that now,
`cmake -DCPPAD_HOME=$CPPAD_HOME ..`
does work and i can compile the examples. But just using the cppAD version in my usr/include folder `cmake ..` does produce an error, now actually a different error.

> /Documents/GitHub/CppADCodeGen2/build/example$ make example_lagrangian
> Scanning dependencies of target lagrangian
> [100%] Building CXX object example/CMakeFiles/lagrangian.dir/lagrangian.cpp.o
> In file included from /home/orca/Documents/GitHub/CppADCodeGen2/include/cppad/cg/extra/extra.hpp:20:0,
>                  from /home/orca/Documents/GitHub/CppADCodeGen2/include/cppad/cg/cppadcg.hpp:151,
>                  from /home/orca/Documents/GitHub/CppADCodeGen2/include/cppad/cg.hpp:18,
>                  from /home/orca/Documents/GitHub/CppADCodeGen2/example/lagrangian.cpp:18:
> /home/orca/Documents/GitHub/CppADCodeGen2/include/cppad/cg/extra/sparse_forjac_hessian.hpp: In function ‘size_t CppAD::cg::colorForwardJacobianHessian(const CppAD::ADFun<Base>&, const VectorSet&, const VectorSet&, CppAD::cg::SparseForjacHessianWork&)’:
> /home/orca/Documents/GitHub/CppADCodeGen2/include/cppad/cg/extra/sparse_forjac_hessian.hpp:247:38: error: ‘local’ has not been declared
>      using SparsityPattern = typename local::internal_sparsity<Set_type>::pattern_type;

and a lot more errors all related to the sparse functionality.

**Comment by joaoleal** [comment]
This appears to be related to https://github.com/joaoleal/CppADCodeGen/issues/7#issuecomment-400470330
The version of CppAD in 16.04 (https://packages.ubuntu.com/xenial/cppad) is not compatible with the current version of CppADCodeGen.
You could consider installing the version from 18.04 (https://packages.ubuntu.com/bionic/cppad).

**Comment by alexliniger** [comment]
Installing the 2017 version of CppAD in a local folder as done in the [CI](https://travis-ci.org/joaoleal/CppADCodeGen/jobs/439360763/config) of the project and then make CppADCodeGen using `cmake -DCPPAD_HOME=$CPPAD_HOME ..` solved the issue for me.
But I assume updating to 18.04 is anyhow a good idea.
