### ISSUE TITLE
Error case for sparse Jacobian creation

### ISSUE THREAD

**Issue by guestieng** [joaoleal/CppADCodeGen#24]
Hello,
there occurs a "cppad" error during the code creation of a "sparse" Jacobian.
Please see a code example below (tested in Ubuntu (Wsl, g++) and Windows (VS 2015)):
```c++
#include <string.h>
#include <cppad/cg.hpp>
#include <cppad/cg/support/cppadcg_eigen.hpp>  

using namespace CppAD;
using namespace CppAD::cg;

typedef CppAD::cg::CG<double> CGD; 
typedef CppAD::AD<CGD> ADCG;
typedef Eigen::Matrix<ADCG, Eigen::Dynamic, 1> ADCGvec;

void ThisAdFunc(ADCGvec& adscalar, const ADCGvec& advec, int dim1, int dim2, int dim3) {
        adscalar(0) = 0;
        double testCoeff = 0;
	for (int ii = 0; ii < dim2; ++ii) {
		for (int jj = 0; jj < dim1; ++jj) {			
			adscalar[0] = adscalar[0] + advec((ii*dim1 + jj) * dim3 + 0)*advec((ii*dim1 + jj) * dim3 + 0)
				+ testCoeff*advec((ii*dim1 + jj) * dim3 + 1)*advec((ii*dim1 + jj) * dim3 + 1)
				+ advec((ii*dim1 + jj) * dim3 + 2)*advec((ii*dim1 + jj) * dim3 + 2);
		}
	}
}

int main(void) {
        int dim1 = 40;
	int dim2 = 10;
        int dim3 = 3;

        ADCGvec thisAdvec(dim1*dim2*dim3);
	ADCGvec thisAdscalar(1);
	CppAD::Independent(thisAdvec);
	ThisAdFunc(thisAdscalar, thisAdvec, dim1, dim2, dim3);

        CppAD::ADFun<CGD> adfun(thisAdvec, thisAdscalar);
        CppAD::cg::ModelCSourceGen<double> cgen(adfun, "adModel");
	
        //  test sparsity:
        cgen.setCreateSparseJacobian(true);
	std::vector<size_t> mappingCols, mappingRows;
	for (int jj = 0; jj < thisAdvec.size(); ++jj) {			
		mappingCols.push_back( jj);
		mappingRows.push_back(0);			
	}
	cgen.setCustomSparseJacobianElements(mappingRows, mappingCols);

        CppAD::cg::ModelLibraryCSourceGen<double> libcgen(cgen);
        CppAD::cg::DynamicModelLibraryProcessor<double> dynLibProc(libcgen, "<path of dynamic lib.>");
        CppAD::cg::GccCompiler<double> compiler("<compiler path>");
        string storageDir = "<code storage directory>";
	compiler.setSaveToDiskFirst(true);
	compiler.setTemporaryFolder(storageDir );
	compiler.setSourcesFolder(storageDir );
	dynLibProc.createDynamicLibrary(compiler); 		

        return 0;
}
```
Note, that the error appears if one sets "testCoeff = 0" in the code above.
Moreover, it's obviously unrelated to the values of the dimensions dim1, dim2, dim3.

**Comment by joaoleal** [comment]
When the value of `testCoeff` is set to zero, the sparsity pattern is also being changed.
When `testCoeff != 0`, then the jacobian spartity pattern will include an entry for variable 1 when `ii = 0` and `jj = 0` from the section:
```C++
testCoeff * advec((ii * dim1 + jj) * dim3 + 1) * advec((ii * dim1 + jj) * dim3 + 1)
// which is
testCoeff * advec((0 * dim1 + jj) * dim3 + 1) * advec((0 * dim1 + 0) * dim3 + 1)
// which is
testCoeff * advec(1) * advec(1)
```

The call to `cgen.setCustomSparseJacobianElements(mappingRows, mappingCols)` assumes the elements to be a subset of the full sparsity pattern.
The failure is inside `ADFun<Base>::SparseJacobianReverse()` which checks whether the provided elements are part of the sparsity pattern.
However, the spartity pattern does not include the variable 1 when `testCoeff = 0`.

**Comment by guestieng** [comment]
Ok, but by speaking about a failure do you mean that this is expected from the developer point of view or may this be considered as a bug?
From the point of view of a user, this behaviour is rather unexpected, since often you cannot foresee whether "numeric" coefficients like testCoeff will become zero or not, e.g., when you implement an error function for an optimization algorithm and respective coefficients are linear combinations of other "numeric" coefficients.

**Comment by joaoleal** [comment]
At the moment it is expected for the developer to provide a correct sparsity pattern (would you really want to receive constant zeros in a sparse Jacobian/Hessian?).
CppadCodeGen does not perform any additional checks regarding the sparsity provided by the user and just forwards it to CppAD which, in turn, expects the developer to provide the correct sparsity.

The common use case to define a custom sparsity is to remove some elements which are not needed.
For this, it possible to compute the sparsity using `CppAD::ADFun<CGD>`, remove the non-desired elements and then provide it to CppADCodeGen.
One would use the same strategy if we were just using CppAD.

CppAD now has explicit support for parameters, which will soon also be supported by CppADCodeGen (see [feature/parameters](https://github.com/joaoleal/CppADCodeGen/tree/feature/parameters) ).
This will reduce the likelihood of `setCustomSparseJacobianElements` being needed.
