### ISSUE TITLE
Best practice for deleting dynamic libraries at program exit

### ISSUE THREAD

**Issue by markusgft** [joaoleal/CppADCodeGen#27]
In my applications, I use CppADCodeGen in the JIT-mode, therefore I compile dynamic libraries at runtime. 
After every program execution, a *.so file is left somewhere in my directories. So far, I have used a script to simply clean up after CppADCG - but anyway I've been wondering for a while now: is there an officially supported way to delete the *.so files after they are not needed any more, e.g. at destruction time?
Thanks a lot in advance, and keep up the great work!

**Comment by joaoleal** [comment]
Hello Markus,

If you are not reusing the dynamic library between executions you may be interested in using JIT with LLVM/Clang.
This alternative does not require the creation of a dynamic library in disk, it is all done in memory.
I've added an example here: [example/jit_linux.cpp](https://github.com/joaoleal/CppADCodeGen/blob/master/example/jit_linux.cpp).

If you would like to reuse the dynamic library between executions, you could add additional information regarding whether or not the model is up to date using custom functions (see [ModelLibraryCSourceGen::addCustomFunctionSource()](https://github.com/joaoleal/CppADCodeGen/blob/master/include/cppad/cg/model/model_library_c_source_gen.hpp) ) which can then be used through [FunctorModelLibrary::loadFunction()](https://github.com/joaoleal/CppADCodeGen/blob/master/include/cppad/cg/model/functor_model_library.hpp).

**Comment by markusgft** [comment]
Dear @joaoleal , thanks a lot for your quicky reply! I will check out your proposal as soon as possible!
