### ISSUE TITLE
Compiler error with newest release on Ubuntu 16.04

### ISSUE THREAD

**Issue by braunzel** [joaoleal/CppADCodeGen#36]
I am trying to compile code which employs CppAD-CG on Ubuntu 16.04 with clang++ (3.6).
I run into the following compiler error, coming directly from one of the pattern headers...:
```
In file included from /usr/local/include/cppad/cg.hpp:18:
In file included from /usr/local/include/cppad/cg/cppadcg.hpp:183:
/usr/local/include/cppad/cg/patterns/iter_equation_group.hpp:253:68: fatal error: default initialization of an object of const type 'const std::map<size_t, std::set<size_t> >' (aka 'const map<unsigned long, set<unsigned long> >') without a user-provided default constructor
const std::map<size_t, std::set<size_t> > IterEquationGroup<Base>::EMPTYMAPSETS;         
```
If I understand it right, the problem might be the following: the default constructor for std::set() has only been made availble from C++14 onwards, for C++11 only compilers it does not exist, see also [here](http://www.cplusplus.com/reference/set/set/set/) and [here](https://stackoverflow.com/questions/7411515/why-does-c-require-a-user-provided-default-constructor-to-default-construct-a).

**Comment by joaoleal** [comment]
The issue might be the std library or compiler version you are using.
C++11 does have an "empty" constructor for set:
```C++
explicit set (const key_compare& comp = key_compare(),
              const allocator_type& alloc = allocator_type());
```
and for map:
```C++
explicit map (const key_compare& comp = key_compare(),
              const allocator_type& alloc = allocator_type());
```
The follow code compiles in clang++5 with c++11 (pedantic):
```C++
#include <set>
#include <map>
 
int main()
{
    std::set<int> s;
    std::map<int, std::set<int>> m;
    return 0;
}
```
https://coliru.stacked-crooked.com/view?id=4ef526ec0892b174

**Comment by joaoleal** [comment]
The tests are now also compiled with clang 8.0 in Travis.

**Comment by braunzel** [comment]
Okay, thank you very much for the clarification!
