### ISSUE TITLE
Using Eigen::Vector instead of std::vector in example fails

### ISSUE THREAD

**Issue by awernerdlr** [joaoleal/CppADCodeGen#4]
First: Great Work! This provides sparse derivatives without memory allocations as far as I
understand. Before, I was using Eigen::AutoDiffScalar<Eigen::SparseVector<double>>.

Here a slightly adapted code from the trivial example. The code uses Eigen::Vector inplace of std::vector, but somehow this does not compile with gcc-5 oder clang-3.7. 
``
#include <iosfwd>
#include <vector>
#include <cppad/cg.hpp>
#include <cppad/example/cppad_eigen.hpp>

int main() {
    // use a special object for source code generation
    typedef CppAD::cg::CG<double> CGD; // this is the code generation type
    typedef CppAD::AD<CGD> ADCG;
    
    // independent variable vector
    Eigen::Matrix<ADCG,Eigen::Dynamic,1> x(1);
    CppAD::Independent(x);

    // dependent variable vector 
    Eigen::Matrix<ADCG,Eigen::Dynamic,1> y(1);

    y = 1. * x;
    // This works: 
    //y = CGD(1.) * x;

    CppAD::ADFun<CGD> fun(x, y);
}
``
Most important is also, that this code works when using 
typedef CppAD::AD<double> ADCG;

I tried to dig into this and from my guesswork somewhere in the clang error messages it says:
/home_local/wern_al/optimalwalk_env_gcc5/install/include/eigen3/Eigen/src/Core/../plugins/CommonCwiseBinaryOps.h:50:29: note: 
      candidate template ignored: substitution failure [with T = double]: no type named 'type'
      in 'Eigen::internal::promote_scalar_arg<CppAD::AD<CppAD::cg::CG<double> >, double,
      false>'
EIGEN_MAKE_SCALAR_BINARY_OP(operator*,product)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~

Here Eigen tries to promote the type (double->ADCG), but this fails. I do not understand this
because the NumTraits are available for the CppAD<T> template.

**Comment by joaoleal** [comment]
I've never used eigen with `AD<CG<Base>>`.
Probably there is a need to create a file similar to cppad_eigen.hpp for `CppAD::AD<CppAD::cg::CG<Base>>`.
I currently have eigen 3.3.2 installed, but it seems that the CppAD example does not compile (even without CppADCodeGen).
Which version of eigen are you using?

**Comment by awernerdlr** [comment]
Hi,
 im using cppad-20170716 (aka the current master). The cmake configuration seems to be a bit broken, but i can execute "make check_speed_cppad" which successfully runs this test. Im using Eigen 3.3.2.

I can also compile the cppad file test_more/general/cppad_eigen.cpp with clang and gcc.

However I continued work after posting this and I am no longer sure that this is an issue which is in CppADCodeGen. Hence i posted: [this on stackoverflow](https://stackoverflow.com/questions/45220606/combining-eigen-and-cppad).
I can provide more details tomorrow.

**Comment by joaoleal** [comment]
I was able to get the cppad example it to compile and by copying the cppad_eigen.hpp contents from master.
So I was able to reproduce your findings.
I tried defining `NumTraits< CppAD::AD<CppAD::cg::CG<double> > >` but it is still not able to find an implementation for `promote_scalar_arg`.
I was expecting it to use:
````
template<typename S,typename T>
struct promote_scalar_arg<S,T,false> : promote_scalar_arg_unsupported<S,T,typename NumTraits<S>::Literal> {};
````
if `NumTraits<CppAD::AD<CppAD::cg::CG<double> >>::Literal` was defined but it does not.

**Comment by awernerdlr** [comment]
I think I got something here. I basically extended cppad_eigen.hpp in the following way:

```
namespace Eigen {
     template <typename T> struct NumTraits< CppAD::cg::CG<T> >
     {     // type that corresponds to the real part of an AD<Base> value
          typedef CppAD::cg::CG<T>   Real;
          // type for AD<Base> operations that result in non-integer values
          typedef CppAD::cg::CG<T>   NonInteger;
          // type for nested value inside an AD<Base> expression tree
          typedef CppAD::cg::CG<T>   Nested;
          //
          typedef CppAD::cg::CG<T>   Literal;

          enum {
               // does not support complex Base types
               IsComplex             = 0 ,
               // does not support integer Base types
               IsInteger             = 0 ,
               // only support signed Base types
               IsSigned              = 1 ,
               // must initialize an AD<Base> object
               RequireInitialization = 1 ,
               // computational cost of the corresponding operations
               ReadCost              = 1 ,
               AddCost               = 2 ,
               MulCost               = 2
          };
     };

     template <class Base> struct NumTraits< CppAD::AD<Base> >
          : NumTraits<Base>
     {     // type that corresponds to the real part of an AD<Base> value
          typedef CppAD::AD<Base>   Real;
          // type for AD<Base> operations that result in non-integer values
          typedef CppAD::AD<Base>   NonInteger;
          // type for nested value inside an AD<Base> expression tree
          typedef CppAD::AD<Base>   Nested;

          enum {
               // does not support complex Base types
               IsComplex             = 0 ,
               // does not support integer Base types
               IsInteger             = 0 ,
               // only support signed Base types
               IsSigned              = 1 ,
               // must initialize an AD<Base> object
               RequireInitialization = 1 ,
               // computational cost of the corresponding operations
               ReadCost              = 1 ,
               AddCost               = 2 ,
               MulCost               = 2
          };
     };
     template<typename Base, typename BinOp>
         struct ScalarBinaryOpTraits<CppAD::AD<Base>,Base,BinOp>
         {
             typedef CppAD::AD<Base> ReturnType;
         };

     template<typename Base, typename BinOp>
         struct ScalarBinaryOpTraits<Base,CppAD::AD<Base>,BinOp>
         {
             typedef CppAD::AD<Base> ReturnType;
         };
     // promote directly from double: breaks the above
     template<typename T, typename BinOp>
         struct ScalarBinaryOpTraits<CppAD::AD<CppAD::cg::CG<T> >,T,BinOp>
         {
             typedef CppAD::AD<CppAD::cg::CG<T> > ReturnType;
         };

     template<typename T, typename BinOp>
         struct ScalarBinaryOpTraits<T,CppAD::AD<CppAD::cg::CG<T> >,BinOp>
         {
             typedef CppAD::AD<CppAD::cg::CG<T> > ReturnType;
         };
} // namespace Eigen
    
namespace CppAD {
          // functions that return references
          template <class Base> const AD<Base>& conj(const AD<Base>& x)
          {     return x; }
          template <class Base> const AD<Base>& real(const AD<Base>& x)
          {     return x; }

          // functions that return values (note abs is defined by cppad.hpp)
          template <class Base> AD<Base> imag(const AD<Base>& x)
          {     return CppAD::AD<Base>(0.); }
          template <class Base> AD<Base> abs2(const AD<Base>& x)
          {     return x * x; }
}

Just tested on some minor examples.
```

**Comment by joaoleal** [comment]
Thank you!
I've added a new file to CppADCodeGen at include/cppad/cg/support/cppadcg_eigen.hpp.

**Comment by awernerdlr** [comment]
Just some feedback here:
My application, a rigid inverse dynamics inverse dynamics algorithm works now. Previously I used this with Eigen::AutoDiffScalar<SparseVector<double>> as Scalar type, now with CppAD::AD<CppAD::cg::CG<double>>. I do use sparse derivatives to hand them over to IpOpt (saw you have forked it) down the road. This is an inverse dynamics for a system with currently 9 dof so 27 input variable and 9 output variables.  I verified correctness and see a factor 200 speed improvement over my previous solution. The previous solution was slowed down by memory allocations (SparseVector!) mostly. Interestingly the speedup drops when I use significantly larger models, e.g. with 55 dof (165 inputs) and 55 output variables the speedup in around 20.

It took ~2 days to get this running, including the small drama above. 

Thanks a lot!

**Comment by joaoleal** [comment]
Glad to hear it worked well!
Speed can depend on the options you used to create the library with CppADCodeGen.
For instance, using 
````C++
ModelCSourceGen<double> cgen(fun, "Lagrangian");
cgen.setCreateSparseJacobian(true);
cgen.setCreateSparseHessian(true);
cgen.setCreateForwardOne(true); // reduces performance, use cgen.setSparseJacobianReuse1stOrderPasses(false) 
cgen.setCreateReverseOne(true); // reduces performance, use cgen.setSparseJacobianReuse1stOrderPasses(false) 
cgen.setCreateReverseTwo(true); // reduces performance, use cgen.setSparseHessianReusesRev2(false)
````
can reduce the performance.
I don't know if you are using it like this, but for Ipopt you probably do not need Forward/ReverseOne and ReverseTwo.
You can also select the elements you need in the Jacobian and Hessian (in case only some of the model variable are decision variables).

My fork of Ipopt is not related with CppADCodeGen.
It only has some simple changes to make it easier to use NLP sensitivities.
