### ISSUE TITLE
New release of CppADCodeGen

### ISSUE THREAD

**Issue by proyan** [joaoleal/CppADCodeGen#41]
Hi Joel,
Thanks for this nice piece of software.
I wonder if you have any plans to release a new version that is compatible with cppad 2020? I see that the last release was made for v2018, and it was more that a year ago.
It would be helpful for us to maintain build compatibility for our software as well.

Best,
Rohan

**Comment by proyan** [comment]
Hi Joel,

I have one other request. Would it be possible to do version verification of cppad inside the CMakeLists file? Currently cppad is checked, but no minimum version is imposed. The current master branch puts the CppAD requirement as (2020) in the README file, but it would be nice if this was followed with a check in CMakeLists, since there is no backward compatibility with CppAD 2019 or 2018 or others.

Thanks again,
Rohan

**Comment by joaoleal** [comment]
Hello Rohan,

I should be releasing a new version soon (the master branch is compatible with CppAD 2020).
Checking the version of CppAD in CMake is a good suggestion. I'll see what can be done about this.

Kind regards,
João

**Comment by proyan** [comment]
Thanks João

Just a heads up, https://github.com/joaoleal/CppADCodeGen/blob/master/pkgconfig/cppadcg.pc.in#L19 might also be in need of an update :)

Best, Rohan

**Comment by joaoleal** [comment]
Created a branch with the check for the CppAD version: [feature/check-cppad-version](https://github.com/joaoleal/CppADCodeGen/tree/feature/check-cppad-version)
