### ISSUE TITLE
PkgConfig and CppAD version

### ISSUE THREAD

**Issue by francofusco** [joaoleal/CppADCodeGen#48]
I did a fresh install of CppAD (v 2020) and of CppADCodeGen. Everything seems to be fine for now, except for one minor issue with PkgConfig (probably related to #41 and #43?): after configuring pkgconfig/cppadcg.pc.in, the version of CppAD is left blank, i.e., the corresponding line reads as
```
Requires:     cppad >=
```
I am not sure if I did some mistake - perhaps I forgot to set some variable/option while running CMake...
To install CppAD is simply cloned it and followed the "classical" build flow:
```
cmake ..
make
make install
```
and the same for CppADCodeGen (skipping the plain `make` step). Do you have any suggestion of what I could have done wrong? Thanks in advance!

**Comment by joaoleal** [comment]
There was a missing variable. It is now fixed in develop.
I will merge it to master once the tests pass and then release the version 1.4.1.

**Comment by francofusco** [comment]
That's perfect, I'll wait for the merge. Thanks!
