### ISSUE TITLE
multiple definition of readStringFromFile

### ISSUE THREAD

**Issue by bradbell** [joaoleal/CppADCodeGen#50]
Using version 2.4.1 I get the following message

    ... snip ...
    multiple definition of `CppAD::cg::readStringFromFile(
        std::__cxx11::basic_string<char, std::char_traits<char>, 
        std::allocator<char> > const&)'; 
    ... snip ...

The following patch seems to fix the problem:

    sed -i include/cppad/cg/util.hpp \
        -e 's|^std::string readStringFromFile(|inline &|'

**Comment by joaoleal** [comment]
Release 2.4.2 with this bugfix.
