### ISSUE TITLE
Conversion error in getCustomLibraryExtension()

### ISSUE THREAD

**Issue by EmbersArc** [joaoleal/CppADCodeGen#52]
Getting `error: cannot convert ‘const std::unique_ptr<const std::__cxx11::basic_string<char> >’ to ‘const string*’ {aka ‘const std::__cxx11::basic_string<char>*’} in return` while compiling.

https://github.com/joaoleal/CppADCodeGen/blob/640fffb8c74236062fe5f9b98164f54b5f4ca14e/include/cppad/cg/model/dynamic_lib/dynamic_library_processor.hpp#L84

Explicit casting seems to fix this.

Compiler: GCC 9.2.1 and Clang 9.0.1
CppAD: 20200000.2
CppADCodegen: 2.4.2

**Comment by bradbell** [comment]
I have seen this error using g++, but it went away when I changed to just using clang. Which compiler is generating your error message ?

**Comment by EmbersArc** [comment]
It's in both gcc and clang with C++17.

**Comment by EmbersArc** [comment]
Calling `_customLibExtension.get()` might be the the easiest fix.

**Comment by joaoleal** [comment]
I'll add the  `.get()` so that it will compile with your gcc/clang.

**Comment by acxz** [comment]
Thx for the fix! When can we expect this change to be released in master or a new release? (It is build breaking for me rn)

**Comment by joaoleal** [comment]
New release 2.4.3 with the fix.

**Comment by acxz** [comment]
Sweet! Can we go ahead and close this issue?
