### ISSUE TITLE
Temporary folder location

### ISSUE THREAD

**Issue by proyan** [joaoleal/CppADCodeGen#58]
Hi João Rui Leal,
I've been trying to use your CppADCodeGen library to generate fast c code for our problems, and have recently integrated it in our optimization solver Crocoddyl(https://github.com/loco-3d/crocoddyl).

I have a problem which deals with the temporary folder `cppadcg_tmp` that gets created by the compiler (https://github.com/joaoleal/CppADCodeGen/blob/master/include/cppad/cg/model/compiler/abstract_c_compiler.hpp#L45). This hardcoded value is quite restrictive if the user does not have permission to create a folder in that directory.

Could we move this directory to `/tmp` for example? Or would you have some suggestion to deal with this?

Best,
Rohan

**Comment by proyan** [comment]
The same is true also for the `.so` file, which gets created at the location where the compilation is called. Is it possible to control the location of the output?

**Comment by joaoleal** [comment]
Hello Rohan,

The extension of the dynamic library can also be changed through the `DynamicModelLibraryProcessor`:
```C++
DynamicModelLibraryProcessor processor(modelLibGen, "myLibName");
processor.setCustomLibraryExtension(".so.123");
```
or if you are using the compiler directly:
```C++
GccCompiler gcc;
// ...
gcc.buildDynamic("thirdorder.so.123");
```

The folder `cppadcg_tmp` can also be changed to any folder path in the compiler:
```C++
GccCompiler gcc;
gcc.setTemporaryFolder("/tmp/some/other/path");
```
At the moment the `DynamicModelLibraryProcessor` doesn't have this option but it is easy to add.

If your model compiles fast, it is possible to do the entire compilation using clang/llvm JIT using the `LlvmBaseModelLibraryProcessor`. However, it will compile the model every time you start your process.

**Comment by proyan** [comment]
Thanks João,
I'll try out your suggestions. I wasn't aware that these options existed.
Cheers,
Rohan
