### ISSUE TITLE
Found CppAD version '' but at least version '20200000.1' is required

### ISSUE THREAD

**Issue by sampotter** [joaoleal/CppADCodeGen#62]
Attempting to install CppAD and CppADCodeGen using CMake 3.18.4 on macOS 10.15.6 and running into some issues.

First, I clone the master branch of CppAD, and run:

```
cd CppAD
mkdir build
cd build
cmake ..
make
sudo make install
```

Everything runs fine, no issues.

Next, I clone the master branch of CppADCodeGen, and run:

```
cp CppADCodeGen
mkdir build
cd build
cmake ..
```

and get the error:

```
CMake Error at cmake/FindCppAD.cmake:99 (MESSAGE):
  Found CppAD version '' but at least version '20200000.1' is required
Call Stack (most recent call first):
  CMakeLists.txt:42 (FIND_PACKAGE)
```

Following the instructions [here](https://coin-or.github.io/CppAD/doc/download.htm) I run `grep '^SET(cppad_version' CMakeLists.txt` and get:

```
SET(cppad_version "20200905")
```

Evidently the version is high enough but it isn't getting pulled in by `FindCppAD.cmake`.

Let me know if I made some mistake in the above. I would expect this approach to "just work"... Thanks.

**Comment by joaoleal** [comment]
Hello,

That version has a different version format since it does not have the **X** in "YYYYMMDD.**X**".
CppADCodeGen uses regular expressions to extract the version information from the installed file (CMakeLists.txt is not installed): 
/usr/local/include/cppad/configure.hpp

I'll update the regular expressions to be more flexible.

**Comment by joaoleal** [comment]
Note that this issue would not happen with the CppAD releases since they follow the format "YYYYMMDD.X".

**Comment by sampotter** [comment]
Thanks. Makes sense. I figured it was something like this. Please update when you've fixed this issue. I'll try with the releases in the meantime.

**Comment by joaoleal** [comment]
It is in master and develop branches.

**Comment by sampotter** [comment]
That fixes the problem, thanks.
