### ISSUE TITLE
Using CppADCodeGen and CppAD together, both as header only?

### ISSUE THREAD

**Issue by aespielberg** [joaoleal/CppADCodeGen#7]
I'm trying to use CppADCodegen, CppAD, and eigen3 in a project, all as header-only libraries.  Is there a way to do this in a project using CMake?  I try to include all three directories in my project, as such:

```
target_include_directories(AutodiffEngine PRIVATE ${PROJECT_SOURCE_DIR}/../ExternalLibs/eigen3/Eigen)
target_include_directories(AutodiffEngine PRIVATE ${PROJECT_SOURCE_DIR}/../ExternalLibs/eigen3/unsupported)
target_include_directories(AutodiffEngine PRIVATE ${PROJECT_SOURCE_DIR}/../ExternalLibs/CppAD)
target_include_directories(AutodiffEngine PRIVATE ${PROJECT_SOURCE_DIR}/../ExternalLibs/CppADCodeGen/include)
```

This works fine for Eigen3 and CppAD, but not for codegen.  Is there a way to use CppADCodegen in a similar way?

**Comment by joaoleal** [comment]
What error do you see?
How was CppAD and CppADCodeGen installed?
I'm currently using include_directories() in CppADCodeGen and other projects (which also use eigen).

Please make sure that CppADCodeGen is installed using something like:
```bash
git clone https://github.com/joaoleal/CppADCodeGen.git CppADCodeGen  #<< or download it manually
mkdir cppadcg-build
cd cppadcg-build
cmake ../CppADCodeGen # <<< read next comment
make DESTDIR=XXX/ExternalLibs/CppADCodeGen install # <<< replace XXX
```
If CppAD is not installed in your system, then you have to add an option to `cmake ../CppADCodeGen`:
```bash
cmake -DCPPAD_HOME=XXX/ExternalLibs/CppAD ../CppADCodeGen # <<< replace XXX
```

See the [General installation](https://github.com/joaoleal/CppADCodeGen#general-installation) section in the README.md.

When CppADCodeGen is used in your C++ source-code, CppADCodeGen must be included before CppAD.
Actually, CppAD does not have you be explicitly included since CppADCodeGen does that for you:
```C++
// #include <cppad/cppad.hpp> <<< do not use this here
#include <cppad/cg.hpp>
// #include <cppad/cppad.hpp> <<< this is OK but not required
```

Please let me know if you have any issues!

**Comment by aespielberg** [comment]
Thank you for the quick reply.  When trying to compile, with an 

> #include <cppad/cg.hpp>

 I get the following error:

```
Error (active)	E1696	cannot open source file "cppad/cg/model/threadpool/pthread_pool_c.hpp"			
Error (active)	E1696	cannot open source file "cppad/cg/model/threadpool/pthread_pool_h.hpp"		
Error (active)	E1696	cannot open source file "cppad/cg/model/threadpool/openmp_c.hpp"		
Error (active)	E1696	cannot open source file "cppad/cg/model/threadpool/openmp_h.hpp"		
Error (active)	E0265	class "CppAD::local::sparse_list::pair_size_t" (declared at line 40) is inaccessible
```	
These classes do not appear to exist, either.  It seems from the CMakeLists of threadpool that perhaps these are to be created on build?

The key thing is I'm trying not to build CppAD and install it.  Since it's header only, I'm hoping I can simply include it in my project.  So rather than build something like: 

`cmake -DCPPAD_HOME=MyProject/ExternalLibs/CppAD ../CppADCodeGen`

I'd be looking to out-of-source build:

`cmake -DCPPAD_HOME=MyProject/ExternalLibs/CppAD ../MyProject`

This, however, leads to the above-listed compilation issues when I try to use it.  I have tried to also `add_subdirectory` of both CppAD and CppADCodeGen in my project - but this leads to namespace collisions.

**Comment by joaoleal** [comment]
The missing files are indeed generated during the installation process (its not really a build/compilation step).
You can still use it as a header only library, but you must do the `cmake install` step and then include installation directory in your project instead of the original CppADCodeGen directory.
There are only header files in the installation directory.

This installation step is required to avoid duplicating code inside CppADCodeGen.

**Comment by aespielberg** [comment]
Thank you for the reply again.  Two quick follow-up questions:

a) When I try to point it to the CppAD directory as you suggested, I get the following error:

```
CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CppAD (missing: CPPAD_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCppAD.cmake:67 (find_package_handle_standard_args)
  CMakeLists.txt:40 (FIND_PACKAGE)

```

Do you know why this might be?

b) If I only need to "install" CppADCodegen, and not build it - does this process do anything platform-specific?  Or, what is this process doing?  I am wondering if I can generate the files, and save the generated files in my repository so others can forego this generation process, or if it's smarter to write a script to handle this setup for other users.

**Comment by joaoleal** [comment]
a) The error is related to CMake not finding CppAD. Make sure the path to the CppAD folder is correct. This folder should have the cppad folder inside (CMake looks for cppad/cppad.hpp inside this folder).

b) You can generate the files and copy them to the original folder if you would like (just make sure you do it again when you update CppADCodeGen with a new version).
There is nothing platform specific in the installation step. It just generates header files with string variables that are assigned to the contents of other files (so that your source-code can call CppADCodeGen to compile other source-code). 
For instance, the generated file cppad/cg/model/threadpool/openmp_c.hpp has a string with the content of the file include/cppad/cg/model/threadpool/openmp.c.

I just realized that there are additional folders in the installation directory:
install_dir/usr/local/include/

**Comment by aespielberg** [comment]
Something weird happened, and I must confess my knowledge of CMake is a little bit lacking, so maybe someone knows why.  CPPAD_INCLUDE_DIR showed up as an option to populate in the CMake UI, but it actually needed CPPAD_INCLUDE_DIRS.  Once I added this with the correct path, a) went away. 

For b), some files are generated, and I copy over the new threadpool files generated.  Now, on compiling source_generation_c.cpp, I get a lot of errors.  Any thoughts?

`Something weird happened, and I must confess my knowledge of CMake is a little bit lacking, so maybe someone knows why.  CPPAD_INCLUDE_DIR showed up as an option to populate in the CMake UI, but it actually needed CPPAD_INCLUDE_DIRS.  Once I added this with the correct path, a) went away. 

For b), some files are generated, and I copy over the new threadpool files generated.  Now, on compiling source_generation_c.cpp, I get a lot of errors: 

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0265	class "CppAD::local::sparse_list::pair_size_t" (declared at line 40) is inaccessible	autodiffproject	e:\ResearchCode\autodiffproject\autodiffproject\ExternalLibs\CppAD\cppad\local\sparse_list.hpp	1385	
Warning	C4267	'=': conversion from 'size_t' to 'long', possible loss of data	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\sectioned_index_pattern.hpp	141	
Warning	C4267	'initializing': conversion from 'size_t' to 'long', possible loss of data	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\sectioned_index_pattern.hpp	145	
Warning	C4267	'initializing': conversion from 'size_t' to 'long', possible loss of data	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\sectioned_index_pattern.hpp	146	
Warning	C4267	'argument': conversion from 'size_t' to 'long', possible loss of data	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\sectioned_index_pattern.hpp	179	
Warning	C4267	'argument': conversion from 'size_t' to 'long', possible loss of data	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\sectioned_index_pattern.hpp	189	
Warning	C4267	'argument': conversion from 'size_t' to 'long', possible loss of data	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\sectioned_index_pattern.hpp	191	
Error	C2672	'std::max': no matching overloaded function found	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\index_pattern_impl.hpp	41	
Error	C2780	'_Ty std::max(std::initializer_list<_Elem>)': expects 1 arguments - 2 provided	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\index_pattern_impl.hpp	41	
Error	C2782	'const _Ty &std::max(const _Ty &,const _Ty &) noexcept(<expr>)': template parameter '_Ty' is ambiguous	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\index_pattern_impl.hpp	41	
Error	C2784	'const _Ty &std::max(const _Ty &,const _Ty &) noexcept(<expr>)': could not deduce template argument for 'const _Ty &' from 'unsigned __int64'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\index_pattern_impl.hpp	41	
Error	C2784	'_Ty std::max(std::initializer_list<_Elem>,_Pr)': could not deduce template argument for 'std::initializer_list<_Elem>' from 'unsigned long'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\index_pattern_impl.hpp	41	
Error	C2780	'const _Ty &std::max(const _Ty &,const _Ty &,_Pr) noexcept(<expr>)': expects 3 arguments - 2 provided	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\index_pattern_impl.hpp	41	
Error	C2672	'std::min': no matching overloaded function found	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\index_pattern_impl.hpp	41	
Error	C2780	'_Ty std::min(std::initializer_list<_Elem>)': expects 1 arguments - 2 provided	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\index_pattern_impl.hpp	41	
Error	C2780	'const _Ty &std::min(const _Ty &,const _Ty &,_Pr) noexcept(<expr>)': expects 3 arguments - 2 provided	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\index_pattern_impl.hpp	41	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	217	
Error	C2433	'CppAD::cg::NearEqual': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	217	
Error	C2365	'CppAD::cg::NearEqual': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	217	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	217	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	218	
Error	C2433	'CppAD::cg::NearEqual': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	218	
Error	C2365	'CppAD::cg::NearEqual': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	218	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	218	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	206	
Error	C2433	'CppAD::cg::GreaterThanZero': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	206	
Error	C2365	'CppAD::cg::GreaterThanZero': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	206	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	206	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	207	
Error	C2433	'CppAD::cg::GreaterThanOrZero': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	207	
Error	C2365	'CppAD::cg::GreaterThanOrZero': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	207	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	207	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	208	
Error	C2433	'CppAD::cg::LessThanZero': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	208	
Error	C2365	'CppAD::cg::LessThanZero': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	208	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	208	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	209	
Error	C2433	'CppAD::cg::LessThanOrZero': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	209	
Error	C2365	'CppAD::cg::LessThanOrZero': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	209	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	209	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	210	
Error	C2433	'CppAD::cg::abs_geq': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	210	
Error	C2365	'CppAD::cg::abs_geq': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	210	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	210	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	213	
Error	C2433	'CppAD::cg::EqualOpSeq': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	213	
Error	C2365	'CppAD::cg::EqualOpSeq': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	213	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	213	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	216	
Error	C2433	'CppAD::cg::NearEqual': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	216	
Error	C2365	'CppAD::cg::NearEqual': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	216	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	216	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	221	
Error	C2460	'CppAD::cg::CondExp': uses 'CppAD::cg::CG<float>', which is being defined	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	221	
Error	C2433	'CppAD::cg::CondExp': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	221	
Error	C2365	'CppAD::cg::CondExp': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	221	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	226	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	228	
Error	C2460	'CppAD::cg::sign': uses 'CppAD::cg::CG<float>', which is being defined	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	228	
Error	C2433	'CppAD::cg::sign': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	228	
Error	C2365	'CppAD::cg::sign': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	228	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	228	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	233	
Error	C2460	'CppAD::cg::pow': uses 'CppAD::cg::CG<float>', which is being defined	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	233	
Error	C2433	'CppAD::cg::pow': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	233	
Error	C2365	'CppAD::cg::pow': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	233	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	233	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	234	
Error	C2460	'CppAD::cg::abs': uses 'CppAD::cg::CG<float>', which is being defined	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	234	
Error	C2433	'CppAD::cg::abs': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	234	
Error	C2365	'CppAD::cg::abs': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	234	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	234	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	235	
Error	C2460	'CppAD::cg::fabs': uses 'CppAD::cg::CG<float>', which is being defined	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	235	
Error	C2433	'CppAD::cg::fabs': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	235	
Error	C2365	'CppAD::cg::fabs': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	235	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	235	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	236	
Error	C2460	'CppAD::cg::acos': uses 'CppAD::cg::CG<float>', which is being defined	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	236	
Error	C2433	'CppAD::cg::acos': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	236	
Error	C2365	'CppAD::cg::acos': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	236	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	236	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	237	
Error	C2460	'CppAD::cg::asin': uses 'CppAD::cg::CG<float>', which is being defined	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	237	
Error	C2433	'CppAD::cg::asin': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	237	
Error	C2365	'CppAD::cg::asin': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	237	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	237	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	238	
Error	C2460	'CppAD::cg::atan': uses 'CppAD::cg::CG<float>', which is being defined	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	238	
Error	C2433	'CppAD::cg::atan': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	238	
Error	C2365	'CppAD::cg::atan': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	238	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	238	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	239	
Error	C2460	'CppAD::cg::cos': uses 'CppAD::cg::CG<float>', which is being defined	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	239	
Error	C2433	'CppAD::cg::cos': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	239	
Error	C2365	'CppAD::cg::cos': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	239	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	239	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	240	
Error	C2460	'CppAD::cg::cosh': uses 'CppAD::cg::CG<float>', which is being defined	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	240	
Error	C2433	'CppAD::cg::cosh': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	240	
Error	C2365	'CppAD::cg::cosh': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	240	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	240	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	241	
Error	C2460	'CppAD::cg::exp': uses 'CppAD::cg::CG<float>', which is being defined	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	241	
Error	C2433	'CppAD::cg::exp': 'friend' not permitted on data declarations	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	241	
Error	C2365	'CppAD::cg::exp': redefinition; previous definition was 'function'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	241	
Error	C2238	unexpected token(s) preceding ';'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	241	
Error	C2143	syntax error: missing ';' before '<'	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	242	
Error	C1003	error count exceeds 100; stopping compilation	autodiffproject	e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\cg.hpp	242	
`

**Comment by joaoleal** [comment]
These issues seems to be compiler related. It might be msvc specific.
There are errors related with CppAD and CppADCodeGen (the first one is related to CppAD but most of them are related to CppADCodeGen).
I have never seen these errors before.

You might also have to install CppAD into a local folder so that it is possible to find `CppAD::local::sparse_list::pair_size_t`.

Are you using CppAD20180000.0?

**Comment by aespielberg** [comment]
The first 'error' is a warning, so that's not a big deal.

Can you define what you mean by a local folder?  It is in a folder that is being included by my CMakeLists.txt as include_directories - not a system-wide install.

I am using CppAD20180000.0.

I will see if I can try compiling this with Clang.

**Comment by bradbell** [comment]
You don't need to install CppAD, just run its cmake command and the make check. That will keep all its results in a sandbox. To be specific, below the directory where cmake is downloaded to. See
https://coin-or.github.io/CppAD/doc/cmake.htm
https://coin-or.github.io/CppAD/doc/cmake_check.htm

**Comment by joaoleal** [comment]
I can compile the examples in CppADCodeGen with gcc using CppAD without installing it in Ubuntu.

The first error:
```
Error (active) E0265 class "CppAD::local::sparse_list::pair_size_t" (declared at line 40) is inaccessible autodiffproject e:\ResearchCode\autodiffproject\autodiffproject\ExternalLibs\CppAD\cppad\local\sparse_list.hpp 1385
```
Could be causing the other ones.
It appears to be related with the sparsity pattern and then the following errors in CppADCodeGen are also related with sparsity patterns (index_pattern_impl.hpp):
```
Error C2672 'std::max': no matching overloaded function found autodiffproject e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\index_pattern_impl.hpp 41
Error C2780 '_Ty std::max(std::initializer_list<_Elem>)': expects 1 arguments - 2 provided autodiffproject e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\index_pattern_impl.hpp 41
Error C2782 'const _Ty &std::max(const _Ty &,const _Ty &) noexcept()': template parameter '_Ty' is ambiguous autodiffproject e:\researchcode\autodiffproject\autodiffproject\externallibs\cppadcodegen\include\cppad\cg\patterns\index\index_pattern_impl.hpp 41
(...)
```

**Comment by bradbell** [comment]
What happens if you go into the CppAD install directory and execute
  bin/run_cmake.sh
  cd build
  make check

**Comment by aespielberg** [comment]
I just went through this whole process in Ubuntu, and cannot reproduce the error.  So this seems to be a Windows only issue.  I'll try running that test later today or tomorrow.
