### ISSUE TITLE
Large computational graphs fail at link time

### ISSUE THREAD

**Issue by optstat** [joaoleal/CppADCodeGen#75]
Hello,

I wanted to share a problem I ran into using this very well written and very useful library.  I work using high dimensional models and my computational graphs tend to be large.

If the computational graph reaches a certain threshold, and the number of arrays and symbols exceed 2GB, we run into a relocation truncated to fit error.  You can read more about this kind of error here
https://stackoverflow.com/questions/6093547/what-do-r-x86-64-32s-and-r-x86-64-64-relocation-mean/33289761#33289761

This problem can in principle be addressed by linking with -mcmodel=large or mcmodel=medium flags.  However in this case the library generated by CppADCodeGen requires linking to libc.a, which is built in 32 bit mode.  Therefore the problem persists.

I believe that if the generated code was C++ with linkage to libgcc.a instead, the problem would be addressed.  This in principle should require very little change since from my observations of the generated code all the mathematical operations are supported in C++ and the only difference should be changing the header to include \<cmath\> and of course renaming the files to use a cpp extension. 

I would be happy to make the code changes, but I wanted to understand if that is in principle possible and whether the subsequent loading of the library after compilation would fail if the code was compiled with C++ mangling in the method signatures.

**Comment by bradbell** [comment]
@joaoleal Are you still supporting CppADCodeGen ?

**Comment by joaoleal** [comment]
@bradbell support is limited to weekends ;)

**Comment by optstat** [comment]
I modified the generator to emit c++ code and this issue is resolved. There are cases when the graphs need to be big for high dimensional problems.
