### ISSUE TITLE
Supporting runtime compilation and dynamic linking in MacOSX M1,2 chips

### ISSUE THREAD

**Issue by cmastalli** [joaoleal/CppADCodeGen#83]
Dear all,

Thank you so much for this great package!

As far as I understand from the documentation, CppADCodeGen doesn't support OSX.
Is that correct?

In case the answer is YES, I would appreciate any guidance on how to do it.
Please note that I am not aware of CppADCodeGen details.

Many thanks,
Carlos

**Comment by jcarpent** [comment]
CppADCG does support OSX. I did the portage few years ago. See, for instance, https://github.com/joaoleal/CppADCodeGen/pull/17.
@cmastalli What is the issue?

**Comment by cmastalli** [comment]
Good to know!

My issue is that I have over 30 min compiling a CppADCodeGen library. At this point, I am unsure if I need to still wait for it.
