### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by jcarpent** [joaoleal/CppADCodeGen#89]
Some important fixes have been merged on the master branch of CppADCodeGen.
@joaoleal Would it be possible to proceed to a new release?

I will then update conda and other package managers accordingly.

Thanks in advance,
Best,
Justin

**Comment by joaoleal** [comment]
Hello Justin,

I'll make a new release this weekend (once I am back at home).

Kind regards,
João

A terça, 27/08/2024, 10:06, Justin Carpentier ***@***.***>
escreveu:

**Comment by jcarpent** [comment]
Thanks a lot @joaoleal. Really appreciate it.
Best,
Justin

**Comment by joaoleal** [comment]
I've released version 2.5.0 of CppADCodeGen

**Comment by jcarpent** [comment]
Fantastic
