### ISSUE TITLE
Branching

### ISSUE THREAD

**Issue by neodyme60** [joaoleal/CppADCodeGen#9]
Hi,
I am not an AD expert, I have nested conditions and I am wondering if booleans are supported ? 
Is this possible "If{ //some code } then{//some code} else{//some code}" (with conditions inside braces) ? 
Thank you.

**Comment by jcarius** [comment]
take a look at things like [CppAD::CondExpLt](https://www.coin-or.org/CppAD/Doc/doxydoc/html/namespaceCppAD_a6f693b45b8fbfdb6c3a3ed5d69e5adbc.html)

**Comment by bradbell** [comment]
I would suggest looking at
https://coin-or.github.io/CppAD/doc/condexp.htm

**Comment by neodyme60** [comment]
Thank you very much for your help.

I have another similar question, I did not find a way to do "if...elseif....else".
I basically need to do something similar to what this guy is doing here(beginif/BeginElseIf) with his own AD lib =>[here](https://github.com/BachiLi/dpt/blob/master/src/bsdf.cpp#L26) and [here](https://github.com/BachiLi/dpt/blob/master/src/chad.h#L1476).

Is there a way to do something equivalent with CppAD ?

**Comment by joaoleal** [comment]
CppAD(Codegen) conditional expressions (if/else) can be implemented using;:
 * `out = CondExpLt(a,b,c,d)` --> `if(a < b) {out = c} else {out = d}`,
 *  `out = CondExpLe(a,b,c,d)` --> `if(a <= b) {out = c} else {out = d}`,
 *  `out = CondExpEq(a,b,c,d)` --> `if(a == b) {out = c} else {out = d}`,
 *  `out = CondExpGe(a,b,c,d)` --> `if(a >= b) {out = c} else {out = d}`, and
 *  `out = CondExpGt(a,b,c,d)` --> `if(a > b) {out = c} else {out = d}`.

See:
https://github.com/joaoleal/CppADCodeGen/blob/6a4f6609365cb25a15e691d7357c84d293491472/include/cppad/cg/cond_exp_op.hpp
